### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by corysimmons** [kingdaro/typescript-plugin-tw-template#1]
I've followed config directions but I'm not exactly sure what I'm supposed to be seeing.

I'm not getting any autocomplete on

```tsx
<div css={tw`bg-NoAutoComplete`}>...</div>
```

Also not getting any special errors in VSCode or terminal.

```tsx
<div css={tw`bg-black THROW_AN_ERROR_PLEASE`}>...</div>
```

Will show this (in terminal, not in VSCode hints):

```bash
$ ✕ pie was not found
```

But it also shows that without your plugin...

I'm somewhat new to Typescript so forgive me if it's obvious. Thank you.

**Comment by itsMapleLeaf** [comment]
Could you show your tsconfig, how you've configured it? Also make sure you're using the workspace TS version in VSCode, which you can do by opening the tsconfig (or any TS file), then clicking the TS version number on the bottom right

EDIT: I also just updated the readme with some additional info/disclaimers. More clarity is always a good thing 🙂

**Comment by corysimmons** [comment]
@kingdaro Ah, it was the workspace TS version. Sorry! I'm somewhat new to TS. I figured if I just did `yarn add -D typescript` that VSCode would use that version instead of whatever (global I guess... argh I never install global stuff but `npm ls -g` says otherwise so went ahead and uninstalled it).

Thanks for your help! The plugin works great now!

**Comment by corysimmons** [comment]
btw, I should note `tsconfig.json` didn't show that number in the bottom right, but a `.tsx` file did.

**Comment by tettoffensive** [comment]
@kingdaro @corysimmons Is there anything else I need to set besides using the workspace version of TS? I selected that but it's still not working.

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"]
    },
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "next-env.d.ts",
    "**/*.js",
    "**/*.jsx",
    "**/*.ts",
    "**/*.tsx"
  ],
  "plugins": [{ "name": "typescript-plugin-tw-template" }]
}
```

**Comment by itsMapleLeaf** [comment]
@tettoffensive The `"plugins"` key should be inside `"compilerOptions"`, like so:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"]
    },
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "plugins": [{ "name": "typescript-plugin-tw-template" }]
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "next-env.d.ts",
    "**/*.js",
    "**/*.jsx",
    "**/*.ts",
    "**/*.tsx"
  ],
}
```

**Comment by tettoffensive** [comment]
Nm...ok. I think it's working now. I was just looking for syntax highlighting but I realize that that's not part of the typescript plugin. I need a vscode extension for that.
