### ISSUE TITLE
All Tailwind classes unknown

### ISSUE THREAD

**Issue by teddybradford** [kingdaro/typescript-plugin-tw-template#2]
For some reason all default Tailwind classes are returning warnings for `unknown tailwind class`.

For example:
```js
import React from 'react';
import styled from '@emotion/styled/macro';
import tw from 'twin.macro';

const StyledApp = styled.div([
  tw`
    p-4
  `,
]);
```
When I hover over `p-4` in VS Code, I get the warning `unknown tailwind class "p-4"`.

Any idea why this might be happening?

**Comment by itsMapleLeaf** [comment]
Hey, thanks for opening the issue 🙂 does it work if you put it all on one line?
```js
const StyledApp = styled.div([
  tw`p-4`,
]);
```
If so, that might mean this needs to support multi-line class names (something I didn't have in mind when writing it). Otherwise, it might be a setup issue, or something with the tailwind config

**Comment by teddybradford** [comment]
Thanks for the suggestion! Unfortunately I still get the warning when I only write on a single line.

I've set up a CRA template if you'd like to take a look and see what might be causing the problem.

1. Download my CRA template https://github.com/teddybradford/cra-template-typescript-emotion-tailwind/archive/master.zip
2. Extract zip
3. Run `yarn create react-app my-app --template file:cra-template-typescript-emotion-tailwind-master`
4. Run `cd my-app`
5. Open `src/App.tsx` in VS Code
6. Set VS Code TS version to workspace version
7. Reload VS Code (might not be needed)
8. See warning

**Comment by itsMapleLeaf** [comment]
The tailwind config is in the `src` folder. Move it to the project root, and the plugin should work

**Comment by teddybradford** [comment]
Ah! That seems to have worked. I no longer receive warnings for known Tailwind classes, only unknown ones now (even when using them on multiple lines!).

I do not seem to be getting autocomplete suggestions, though. 🤔

**Comment by itsMapleLeaf** [comment]
Er... hit ctrl+space in the template string? Not sure what the issue there is

**Comment by teddybradford** [comment]
It's very odd. I am getting Emmet Abbreviation suggestions:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/3684553/80519830-95b3c200-8956-11ea-9cb1-0c1adcf96dd8.png">

**Comment by itsMapleLeaf** [comment]
🤔 Tried this exact setup, seeing it on my end
![image](https://user-images.githubusercontent.com/19603573/80520482-1bcc0a80-894f-11ea-8d18-0032f9388008.png)

Verify a few things:
- Make sure you're still on the workspace TS version
- `typescript` and `tailwindcss` should be installed as peer deps

**Comment by teddybradford** [comment]
I must have made a mistake somewhere. I just did a fresh setup and autocomplete is working for me now!

Thank you for your help! 😃
